title: Founder Tribe
description: > # this means to ignore newlines until "baseurl:"
  The community for London's solo founders.
permalink: ':title'
# permalink: ':title'
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://foundertribe.org' # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: JoinTheTribeApp #if your site has a twitter account, enter it here

# Author Settings
author: Maxx Turing # add your name
author-img: # add your photo
about-author: # add description
social-twitter: JoinTheTribeApp # add your Twitter handle
social-instagram: JoinTheTribeApp # add your Instagram handle
social-github: JoinTheTribeApp # add your Github handle
social-linkedin: JoinTheTribeApp # add your Linkedin handle
social-email: maxx@foundertribe.org # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: '/page/:num'

exclude: ['node_modules', 'gulpfile.js', 'package.json', 'yarn.lock']
